import {
    STALKER_SESSION_CONTINUE,
    STALKER_SESSION_CONTROL,
    STALKER_SESSION_OPEN,
    STALKER_SESSION_REQUEST,
} from './ipc-commands';
import {
    IpcCommand,
    type IpcCommandRequest,
    type IpcCommandResponse,
} from './ipc-command.class';
import type { ElectronBridgeApi } from './electron-api.interface';
import {
    STALKER_SESSION_APPLICATION_OPERATIONS,
    type StalkerSessionApplicationOperation,
    type StalkerSessionContinueRequest,
    type StalkerSessionControlRequest,
    type StalkerSessionOpenRequest,
    type StalkerSessionOperationContractMap,
    type StalkerSessionRequest,
    type StalkerSessionRequestOutcome,
} from './stalker-session.interface';

describe('typed IPC commands', () => {
    it('maps STALKER_SESSION_OPEN to exactly one request and response type', () => {
        const request: IpcCommandRequest<typeof STALKER_SESSION_OPEN> = {
            descriptor: {
                connectionMode: 'provisional',
                macAddress: '00:1A:79:00:00:01',
                playlistRef: 'playlist-ref',
                profilePreset: {
                    id: 'mag250-public-5_1-minimal-v1',
                    version: 1,
                },
                provisionalReason: 'import',
                sourceUrl: 'https://portal.test/c/',
            },
        } satisfies StalkerSessionOpenRequest;
        const response: IpcCommandResponse<typeof STALKER_SESSION_OPEN> = {
            attemptRef: 'opaque-attempt',
            challengeRef: 'opaque-origin-challenge',
            finalOrigin: 'https://target.test',
            kind: 'origin-approval-required',
            requestId: 'request-id',
            sourceOrigin: 'https://portal.test',
        };
        const callback = jest.fn<
            void,
            [IpcCommandResponse<typeof STALKER_SESSION_OPEN>]
        >();

        const command = new IpcCommand(STALKER_SESSION_OPEN, callback);
        command.callback(response);

        expect(request.descriptor.sourceUrl).toBe('https://portal.test/c/');
        expect(command.id).toBe(STALKER_SESSION_OPEN);
        expect(callback).toHaveBeenCalledWith(response);
    });

    it('maps STALKER_SESSION_CONTINUE to exactly one request and response type', () => {
        const request: IpcCommandRequest<typeof STALKER_SESSION_CONTINUE> = {
            challengeRef: 'opaque-credential-challenge',
            response: {
                kind: 'credentials',
                password: 'test-only-password',
                username: 'test-only-user',
            },
        } satisfies StalkerSessionContinueRequest;
        const response: IpcCommandResponse<typeof STALKER_SESSION_CONTINUE> = {
            attemptRef: 'opaque-attempt',
            capabilities: {
                authenticatedSession: true,
                playbackContext: true,
            },
            connectionMode: 'provisional',
            endpoint: 'https://portal.test/server/load.php',
            kind: 'ready',
            landingUrl: 'https://portal.test/c/',
            leaseRef: 'opaque-lease',
            persistenceDraft: {
                isFullStalkerPortal: true,
                portalUrl: 'https://portal.test/server/load.php',
                stalkerLandingUrl: 'https://portal.test/c/',
                stalkerRecipeClassifierVersion: 1,
                stalkerRequestRecipe: 'full-session',
            },
            provisionalReason: 'import',
            recipe: 'full-session',
            requestId: 'request-id',
        };

        expect(request.response.kind).toBe('credentials');
        expect(response.kind).toBe('ready');
    });

    it('maps STALKER_SESSION_REQUEST to exactly one request and response type', () => {
        const request: IpcCommandRequest<typeof STALKER_SESSION_REQUEST> = {
            leaseRef: 'opaque-lease',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems,
            parameters: { category: '10', page: 1 },
            // @ts-expect-error Request IDs are generated by Electron main.
            requestId: 'renderer-request-id',
        } satisfies StalkerSessionRequest;
        const response: IpcCommandResponse<typeof STALKER_SESSION_REQUEST> = {
            kind: 'success',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems,
            payload: { items: [], page: 1, total: 0 },
            requestId: 'request-id',
        };

        expect(request.operation).toBe('get-ordered-list');
        expect(response.kind).toBe('success');
    });

    it('preserves operation correlation through IPC and Electron API aliases', () => {
        type CatalogOperation =
            typeof STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems;
        const request: IpcCommandRequest<
            typeof STALKER_SESSION_REQUEST,
            CatalogOperation
        > = {
            leaseRef: 'opaque-lease',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems,
            parameters: { page: 1 },
        };
        const response: IpcCommandResponse<
            typeof STALKER_SESSION_REQUEST,
            CatalogOperation
        > = {
            kind: 'success',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems,
            payload: { items: [] },
            requestId: 'main-request-id',
        };

        const assertApi = (api: ElectronBridgeApi) => {
            const outcome = api.stalkerSessionRequest?.(request);
            outcome?.then((value) => {
                if (value.kind === 'success') {
                    expect(value.payload.items).toEqual([]);
                    // @ts-expect-error Catalog results never expose streamUrl.
                    void value.payload.streamUrl;
                }
            });
        };

        expect(request.operation).toBe('get-ordered-list');
        expect(response.kind).toBe('success');
        expect(assertApi).toBeDefined();
    });

    it('correlates each operation with its request and sanitized result', () => {
        type MissingOperations = Exclude<
            StalkerSessionApplicationOperation,
            keyof StalkerSessionOperationContractMap
        >;
        type ExtraOperations = Exclude<
            keyof StalkerSessionOperationContractMap,
            StalkerSessionApplicationOperation
        >;
        const mapIsExhaustive: [MissingOperations, ExtraOperations] extends [
            never,
            never,
        ]
            ? true
            : false = true;

        const mismatchedRequest: StalkerSessionRequest = {
            leaseRef: 'opaque-lease',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems,
            // @ts-expect-error Catalog requests cannot use EPG parameters.
            parameters: { channelId: 'channel-1' },
        };
        const mismatchedResult: StalkerSessionRequestOutcome = {
            kind: 'success',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CreateLink,
            // @ts-expect-error create-link cannot return a catalog collection.
            payload: { items: [] },
            requestId: 'request-id',
        };

        expect(mapIsExhaustive).toBe(true);
        expect(mismatchedRequest.operation).toBe('get-ordered-list');
        expect(mismatchedResult.kind).toBe('success');
    });

    it('maps STALKER_SESSION_CONTROL to exactly one request and response type', () => {
        const request: IpcCommandRequest<typeof STALKER_SESSION_CONTROL> = {
            action: 'commit',
            attemptRef: 'opaque-attempt',
            // @ts-expect-error Request IDs are generated by Electron main.
            requestId: 'renderer-request-id',
        } satisfies StalkerSessionControlRequest;
        const response: IpcCommandResponse<typeof STALKER_SESSION_CONTROL> = {
            action: 'commit',
            kind: 'success',
            requestId: 'request-id',
        };

        expect(request.action).toBe('commit');
        expect(response.kind).toBe('success');
    });

    it('discriminates persisted and provisional connection descriptors', () => {
        const persistedWithReason: StalkerSessionOpenRequest = {
            descriptor: {
                connectionMode: 'persisted-open',
                macAddress: '00:1A:79:00:00:01',
                playlistRef: 'playlist-ref',
                profilePreset: {
                    id: 'mag250-public-5_1-minimal-v1',
                    version: 1,
                },
                // @ts-expect-error Persisted opens never carry a provisional reason.
                provisionalReason: 'edit',
                sourceUrl: 'https://portal.test/c/',
            },
        };
        const provisionalWithoutReason: StalkerSessionOpenRequest = {
            // @ts-expect-error Provisional opens require their reason.
            descriptor: {
                connectionMode: 'provisional',
                macAddress: '00:1A:79:00:00:01',
                playlistRef: 'playlist-ref',
                profilePreset: {
                    id: 'mag250-public-5_1-minimal-v1',
                    version: 1,
                },
                sourceUrl: 'https://portal.test/c/',
            },
        };

        expect(persistedWithReason.descriptor.connectionMode).toBe(
            'persisted-open'
        );
        expect(provisionalWithoutReason.descriptor.connectionMode).toBe(
            'provisional'
        );
    });

    it('keeps playback context exclusive to a create-link result', () => {
        const catalogOutcome: StalkerSessionRequestOutcome = {
            kind: 'success',
            operation: STALKER_SESSION_APPLICATION_OPERATIONS.CatalogItems,
            payload: { items: [] },
            // @ts-expect-error Catalog success cannot carry playback context.
            playbackContextRef: 'opaque-context',
            requestId: 'main-request-id',
        };

        expect(catalogOutcome.kind).toBe('success');
    });

    it('excludes ready outcomes from application request results', () => {
        const requestOutcome: StalkerSessionRequestOutcome = {
            attemptRef: 'opaque-attempt',
            capabilities: {
                authenticatedSession: true,
                playbackContext: true,
            },
            endpoint: 'https://portal.test/server/load.php',
            // @ts-expect-error Ready belongs only to open/continue outcomes.
            kind: 'ready',
            landingUrl: 'https://portal.test/c/',
            leaseRef: 'opaque-lease',
            persistenceDraft: {
                isFullStalkerPortal: true,
                portalUrl: 'https://portal.test/server/load.php',
                stalkerLandingUrl: 'https://portal.test/c/',
                stalkerRecipeClassifierVersion: 1,
                stalkerRequestRecipe: 'full-session',
            },
            recipe: 'full-session',
            requestId: 'main-request-id',
        };

        expect(requestOutcome.kind).toBe('ready');
    });

    it('keeps secret runtime state out of result DTO examples', () => {
        const outcome: IpcCommandResponse<typeof STALKER_SESSION_OPEN> = {
            kind: 'failure',
            reason: 'request-timeout',
            requestId: 'request-id',
            retryable: true,
            stage: 'handshaking',
        };
        const serializedKeys = collectKeys(outcome);

        expect(serializedKeys).not.toEqual(
            expect.arrayContaining([
                'authorization',
                'cookie',
                'password',
                'random',
                'token',
            ])
        );
    });
});

function collectKeys(value: unknown): string[] {
    if (Array.isArray(value)) {
        return value.flatMap(collectKeys);
    }
    if (typeof value !== 'object' || value === null) {
        return [];
    }

    return Object.entries(value).flatMap(([key, child]) => [
        key.toLowerCase(),
        ...collectKeys(child),
    ]);
}
