import { PlaylistRecentlyViewedItem } from './playlist-recently-viewed.interface';
import { StalkerPortalItem } from './stalker-portal-item.interface';
import type {
    StalkerSessionIdentityOverrides,
    StalkerSessionProfilePreset,
    StalkerSessionRequestRecipe,
    StalkerSessionTransportConfiguration,
} from './stalker-session.interface';

/**
 * An interface that describe the possible states of the playlist update/refresh process
 */
export enum PlaylistUpdateState {
    UPDATED,
    IN_PROGRESS,
    NOT_UPDATED,
}

/**
 * Describes playlist interface
 */
export interface Playlist {
    _id: string;
    title: string;
    filename?: string;
    playlist?: any;
    importDate: string;
    lastUsage: string;
    /**
     * M3U playlists store channel URL strings (`string[]`).
     * Stalker portals store full item objects (`StalkerPortalItem[]`).
     */
    favorites?: (string | StalkerPortalItem)[];
    items?: unknown[];
    header?: unknown;
    count: number;
    url?: string;
    userAgent?: string;
    referrer?: string;
    origin?: string;
    filePath?: string;
    /** M3U-scoped EPG source URLs enabled for automatic import and lookup. */
    epgUrls?: string[];
    /** All M3U EPG source URLs detected from the playlist header. */
    detectedEpgUrls?: string[];
    /** Playlist-local EPG source URLs explicitly enabled by the user. */
    manualEpgUrls?: string[];
    /** Detected playlist EPG source URLs explicitly disabled by the user. */
    disabledEpgUrls?: string[];
    autoRefresh: boolean;
    updateDate?: number;
    updateState?: PlaylistUpdateState;
    position?: number;
    isTemporary?: boolean;
    serverUrl?: string;
    username?: string;
    password?: string;
    macAddress?: string;
    portalUrl?: string;
    /** User-entered Stalker source URL; endpoint discovery starts here. */
    stalkerSourceUrl?: string;
    /** Last verified landing URL used for Referer behavior. */
    stalkerLandingUrl?: string;
    /** Last verified request recipe; treated as a revalidated hint. */
    stalkerRequestRecipe?: StalkerSessionRequestRecipe;
    /** Version of the classifier that established stalkerRequestRecipe. */
    stalkerRecipeClassifierVersion?: number;
    /** Selected coherent Stalker identity preset. */
    stalkerProfilePreset?: StalkerSessionProfilePreset;
    /** Explicit user-owned identity values; blank fields remain absent. */
    stalkerIdentityOverrides?: StalkerSessionIdentityOverrides;
    /** Explicit non-secret transport/profile presentation overrides. */
    stalkerTransportConfiguration?: StalkerSessionTransportConfiguration;
    /** ISO timestamp of the last complete, successful endpoint verification. */
    stalkerLastVerifiedAt?: string;
    recentlyViewed?: PlaylistRecentlyViewedItem[];
    /** Indicates if this is a full stalker portal URL (e.g., /stalker_portal/c) requiring handshake authentication */
    isFullStalkerPortal?: boolean;
    /** Xtream server timezone string for catch-up URL construction */
    serverTimezone?: string;
    /**
     * @deprecated Legacy persisted token. The main-process session runtime
     * removes this field after a successful connection promotion.
     */
    stalkerToken?: string;
    /** Legacy explicit serial number; never generated by the session runtime. */
    stalkerSerialNumber?: string;
    /** Legacy explicit device ID 1; blank means absent. */
    stalkerDeviceId1?: string;
    /** Legacy explicit device ID 2; blank means absent. */
    stalkerDeviceId2?: string;
    /** Optional signature 1 for stalker portal - required by some portals for device verification */
    stalkerSignature1?: string;
    /** Optional signature 2 for stalker portal - required by some portals for device verification */
    stalkerSignature2?: string;
    /** Account info from get_profile call */
    stalkerAccountInfo?: {
        login?: string;
        expireDate?: number;
        tariffPlanName?: string;
        status?: number;
    };
    /** Hidden M3U group titles for the groups view */
    hiddenGroupTitles?: string[];
}
