export interface VpnLocationOption {
    code: string;
    label: string;
}

export const PROTON_VPN_LOCATION_OPTIONS: readonly VpnLocationOption[] = [
    { code: 'FASTEST', label: 'Fastest available' },
    { code: 'HR', label: 'Croatia' },
    { code: 'AL', label: 'Albania' },
    { code: 'AR', label: 'Argentina' },
    { code: 'AU', label: 'Australia' },
    { code: 'AT', label: 'Austria' },
    { code: 'BE', label: 'Belgium' },
    { code: 'BR', label: 'Brazil' },
    { code: 'BG', label: 'Bulgaria' },
    { code: 'CA', label: 'Canada' },
    { code: 'CL', label: 'Chile' },
    { code: 'CO', label: 'Colombia' },
    { code: 'CY', label: 'Cyprus' },
    { code: 'CZ', label: 'Czechia' },
    { code: 'DK', label: 'Denmark' },
    { code: 'EE', label: 'Estonia' },
    { code: 'FI', label: 'Finland' },
    { code: 'FR', label: 'France' },
    { code: 'DE', label: 'Germany' },
    { code: 'GR', label: 'Greece' },
    { code: 'HK', label: 'Hong Kong' },
    { code: 'HU', label: 'Hungary' },
    { code: 'IS', label: 'Iceland' },
    { code: 'IN', label: 'India' },
    { code: 'ID', label: 'Indonesia' },
    { code: 'IE', label: 'Ireland' },
    { code: 'IL', label: 'Israel' },
    { code: 'IT', label: 'Italy' },
    { code: 'JP', label: 'Japan' },
    { code: 'LV', label: 'Latvia' },
    { code: 'LT', label: 'Lithuania' },
    { code: 'LU', label: 'Luxembourg' },
    { code: 'MY', label: 'Malaysia' },
    { code: 'MX', label: 'Mexico' },
    { code: 'MD', label: 'Moldova' },
    { code: 'NL', label: 'Netherlands' },
    { code: 'NZ', label: 'New Zealand' },
    { code: 'NG', label: 'Nigeria' },
    { code: 'NO', label: 'Norway' },
    { code: 'PE', label: 'Peru' },
    { code: 'PH', label: 'Philippines' },
    { code: 'PL', label: 'Poland' },
    { code: 'PT', label: 'Portugal' },
    { code: 'RO', label: 'Romania' },
    { code: 'RS', label: 'Serbia' },
    { code: 'SG', label: 'Singapore' },
    { code: 'SK', label: 'Slovakia' },
    { code: 'SI', label: 'Slovenia' },
    { code: 'ZA', label: 'South Africa' },
    { code: 'KR', label: 'South Korea' },
    { code: 'ES', label: 'Spain' },
    { code: 'SE', label: 'Sweden' },
    { code: 'CH', label: 'Switzerland' },
    { code: 'TW', label: 'Taiwan' },
    { code: 'TH', label: 'Thailand' },
    { code: 'TR', label: 'Turkey' },
    { code: 'UA', label: 'Ukraine' },
    { code: 'GB', label: 'United Kingdom' },
    { code: 'US', label: 'United States' },
    { code: 'VN', label: 'Vietnam' },
];
