import { PLAYBACK_SETTINGS_SEARCH_ENTRIES } from './settings-search-entries-playback';
import { SettingsSearchEntry } from './settings-search.types';

const DASHBOARD_KEYWORDS = ['dashboard', 'home', 'rail', 'row'];

function dashboardRail(
    id: string,
    key: string,
    keywords: readonly string[]
): SettingsSearchEntry {
    return {
        id: `dashboard-rail-${id}`,
        section: 'dashboard',
        labelKey: `SETTINGS.DASHBOARD_RAIL_${key}`,
        descriptionKey: `SETTINGS.DASHBOARD_RAIL_${key}_DESCRIPTION`,
        keywords: [...DASHBOARD_KEYWORDS, ...keywords],
        fallbackId: 'show-dashboard',
    };
}

/**
 * Every searchable settings row, in page order (section order, then row
 * order). Ties in search ranking keep this order, so results read like the
 * settings page itself. A unit test in the web app checks this list against
 * the `data-setting-id` anchors in the section templates.
 */
export const SETTINGS_SEARCH_ENTRIES: readonly SettingsSearchEntry[] = [
    {
        id: 'language',
        section: 'general',
        labelKey: 'SETTINGS.LANGUAGE',
        descriptionKey: 'SETTINGS.LANGUAGE_DESCRIPTION',
        keywords: ['language', 'locale', 'translation'],
    },
    {
        id: 'theme',
        section: 'general',
        labelKey: 'SETTINGS.THEME',
        descriptionKey: 'SETTINGS.THEME_DESCRIPTION',
        keywords: ['theme', 'dark', 'light', 'appearance', 'color'],
    },
    {
        id: 'cover-size',
        section: 'general',
        labelKey: 'SETTINGS.COVER_SIZE',
        descriptionKey: 'SETTINGS.COVER_SIZE_DESCRIPTION',
        keywords: ['poster', 'cover', 'grid', 'card', 'size'],
    },
    {
        id: 'cover-titles',
        section: 'general',
        labelKey: 'SETTINGS.COVER_TITLES',
        descriptionKey: 'SETTINGS.COVER_TITLES_DESCRIPTION',
        keywords: ['poster', 'cover', 'title', 'caption'],
    },
    {
        id: 'startup-behavior',
        section: 'general',
        labelKey: 'SETTINGS.STARTUP_BEHAVIOR',
        descriptionKey: 'SETTINGS.STARTUP_BEHAVIOR_DESCRIPTION',
        keywords: ['startup', 'launch', 'restore', 'last view'],
    },
    {
        id: 'startup-window-mode',
        section: 'general',
        labelKey: 'SETTINGS.STARTUP_WINDOW_MODE',
        descriptionKey: 'SETTINGS.STARTUP_WINDOW_MODE_DESCRIPTION',
        keywords: ['startup', 'window', 'fullscreen', 'maximized'],
        requires: ['startup-window-mode'],
    },
    {
        id: 'show-captions',
        section: 'general',
        labelKey: 'SETTINGS.SHOW_CAPTIONS',
        descriptionKey: 'SETTINGS.SHOW_CAPTIONS_DESCRIPTION',
        keywords: ['subtitles', 'captions', 'cc'],
    },
    {
        id: 'strip-country-prefix',
        section: 'general',
        labelKey: 'SETTINGS.STRIP_COUNTRY_PREFIX',
        descriptionKey: 'SETTINGS.STRIP_COUNTRY_PREFIX_DESCRIPTION',
        keywords: ['channel name', 'country', 'prefix', 'tag'],
    },
    {
        id: 'portal-connectivity-guard',
        section: 'general',
        labelKey: 'SETTINGS.PORTAL_CONNECTIVITY_GUARD',
        descriptionKey: 'SETTINGS.PORTAL_CONNECTIVITY_GUARD_DESCRIPTION',
        keywords: ['network', 'offline', 'connection', 'internet', 'vpn'],
        requires: ['portal-connectivity-guard'],
    },
    ...PLAYBACK_SETTINGS_SEARCH_ENTRIES,
    {
        id: 'epg-view-mode',
        section: 'epg',
        labelKey: 'SETTINGS.EPG_VIEW_MODE',
        descriptionKey: 'SETTINGS.EPG_VIEW_MODE_DESCRIPTION',
        keywords: ['epg', 'tv guide', 'timeline', 'grid', 'programme'],
        requires: ['epg'],
    },
    {
        id: 'epg-offset',
        section: 'epg',
        labelKey: 'SETTINGS.EPG_OFFSET_TITLE',
        descriptionKey: 'SETTINGS.EPG_OFFSET_HINT',
        keywords: ['epg', 'timezone', 'time shift', 'offset', 'hours'],
        requires: ['epg'],
    },
    {
        id: 'epg-sources',
        section: 'epg',
        labelKey: 'SETTINGS.EPG_SOURCE_LIST_TITLE',
        descriptionKey: 'SETTINGS.EPG_SOURCE_FORMATS_HINT',
        keywords: ['epg', 'xmltv', 'tv guide', 'url', 'refresh', 'clear'],
        requires: ['epg'],
    },
    {
        id: 'prefer-uploaded-epg',
        section: 'epg',
        labelKey: 'SETTINGS.PREFER_UPLOADED_EPG_TITLE',
        descriptionKey: 'SETTINGS.PREFER_UPLOADED_EPG_HINT',
        keywords: ['epg', 'xmltv', 'priority', 'provider'],
        requires: ['epg'],
    },
    {
        id: 'show-dashboard',
        section: 'dashboard',
        labelKey: 'SETTINGS.SHOW_DASHBOARD',
        descriptionKey: 'SETTINGS.SHOW_DASHBOARD_DESCRIPTION',
        keywords: ['dashboard', 'home', 'start page'],
    },
    {
        id: 'dashboard-hero',
        section: 'dashboard',
        labelKey: 'SETTINGS.DASHBOARD_HERO',
        descriptionKey: 'SETTINGS.DASHBOARD_HERO_DESCRIPTION',
        keywords: [...DASHBOARD_KEYWORDS, 'banner', 'featured'],
        fallbackId: 'show-dashboard',
    },
    dashboardRail('continue-watching', 'CONTINUE', ['resume', 'progress']),
    dashboardRail('live-favorites', 'LIVE_FAVORITES', ['favorites', 'live']),
    dashboardRail('recent-live', 'RECENT_LIVE', ['recent', 'live']),
    dashboardRail('favorite-vod', 'FAVORITE_VOD', ['favorites', 'movies']),
    dashboardRail('sources', 'SOURCES', ['playlists', 'sources']),
    dashboardRail('xtream-added', 'XTREAM_ADDED', ['xtream', 'new']),
    dashboardRail('tmdb-trending', 'TMDB_TRENDING', ['tmdb', 'trending']),
    dashboardRail('tmdb-recommendations', 'TMDB_RECOMMENDATIONS', [
        'tmdb',
        'recommendations',
    ]),
    {
        id: 'remote-control',
        section: 'remote-control',
        labelKey: 'SETTINGS.REMOTE_CONTROL',
        descriptionKey: 'SETTINGS.REMOTE_CONTROL_DESCRIPTION',
        keywords: ['remote', 'phone', 'mobile', 'companion'],
        requires: ['remote-control'],
    },
    {
        id: 'remote-control-port',
        section: 'remote-control',
        labelKey: 'SETTINGS.REMOTE_CONTROL_PORT',
        descriptionKey: 'SETTINGS.REMOTE_CONTROL_PORT_DESCRIPTION',
        keywords: ['remote', 'port', 'network'],
        requires: ['remote-control'],
        fallbackId: 'remote-control',
    },
    {
        id: 'remote-control-url',
        section: 'remote-control',
        labelKey: 'SETTINGS.REMOTE_CONTROL_URL',
        descriptionKey: 'SETTINGS.REMOTE_CONTROL_URL_DESCRIPTION',
        keywords: ['remote', 'qr code', 'address', 'ip'],
        requires: ['remote-control'],
        fallbackId: 'remote-control',
    },
    {
        id: 'tmdb-enable',
        section: 'tmdb',
        labelKey: 'SETTINGS.TMDB_ENABLE',
        descriptionKey: 'SETTINGS.TMDB_ENABLE_DESCRIPTION',
        keywords: ['tmdb', 'themoviedb', 'metadata', 'posters', 'ratings'],
    },
    {
        id: 'tmdb-api-key',
        section: 'tmdb',
        labelKey: 'SETTINGS.TMDB_API_KEY',
        descriptionKey: 'SETTINGS.TMDB_API_KEY_DESCRIPTION',
        keywords: ['tmdb', 'api key', 'token'],
        fallbackId: 'tmdb-enable',
    },
    {
        id: 'tmdb-m3u-vod-details',
        section: 'tmdb',
        labelKey: 'SETTINGS.TMDB_M3U_VOD_DETAILS',
        descriptionKey: 'SETTINGS.TMDB_M3U_VOD_DETAILS_DESCRIPTION',
        keywords: ['tmdb', 'm3u', 'movies', 'details'],
        fallbackId: 'tmdb-enable',
    },
    {
        id: 'tmdb-cache',
        section: 'tmdb',
        labelKey: 'SETTINGS.TMDB_CACHE',
        descriptionKey: 'SETTINGS.TMDB_CACHE_DESCRIPTION',
        keywords: ['tmdb', 'cache', 'clear', 'storage'],
    },
    {
        id: 'parental-lock-enable',
        section: 'parental',
        labelKey: 'SETTINGS.PARENTAL_LOCK.ENABLE',
        descriptionKey: 'SETTINGS.PARENTAL_LOCK.ENABLE_DESCRIPTION',
        keywords: ['parental', 'lock', 'pin', 'kids', 'children', 'adult'],
    },
    {
        id: 'parental-lock-status',
        section: 'parental',
        labelKey: 'SETTINGS.PARENTAL_LOCK.STATUS',
        keywords: ['parental', 'lock now', 'unlock'],
        fallbackId: 'parental-lock-enable',
    },
    {
        id: 'parental-lock-relock',
        section: 'parental',
        labelKey: 'SETTINGS.PARENTAL_LOCK.RELOCK',
        descriptionKey: 'SETTINGS.PARENTAL_LOCK.RELOCK_DESCRIPTION',
        keywords: ['parental', 'idle', 'timeout', 'relock'],
        fallbackId: 'parental-lock-enable',
    },
    {
        id: 'parental-lock-change-pin',
        section: 'parental',
        labelKey: 'SETTINGS.PARENTAL_LOCK.CHANGE_PIN',
        descriptionKey: 'SETTINGS.PARENTAL_LOCK.CHANGE_PIN_DESCRIPTION',
        keywords: ['parental', 'pin', 'password'],
        fallbackId: 'parental-lock-enable',
    },
    {
        id: 'parental-lock-how-to',
        section: 'parental',
        labelKey: 'SETTINGS.PARENTAL_LOCK.HOW_TO_LOCK',
        descriptionKey: 'SETTINGS.PARENTAL_LOCK.HOW_TO_LOCK_DESCRIPTION',
        keywords: ['parental', 'lock categories', 'groups', 'right-click'],
        fallbackId: 'parental-lock-enable',
    },
    {
        id: 'import-export-data',
        section: 'backup',
        labelKey: 'SETTINGS.IMPORT_EXPORT_DATA',
        descriptionKey: 'SETTINGS.IMPORT_EXPORT_DATA_DESCRIPTION',
        keywords: ['backup', 'restore', 'import', 'export', 'migrate'],
    },
    {
        id: 'remove-all-playlists',
        section: 'reset',
        labelKey: 'SETTINGS.REMOVE_ALL',
        descriptionKey: 'SETTINGS.REMOVE_ALL_DESCRIPTION',
        keywords: ['reset', 'delete', 'remove', 'wipe', 'playlists'],
    },
    {
        id: 'version',
        section: 'about',
        labelKey: 'SETTINGS.VERSION',
        descriptionKey: 'SETTINGS.VERSION_DESCRIPTION',
        keywords: ['version', 'build', 'commit'],
    },
    {
        id: 'app-update',
        section: 'about',
        labelKey: 'SETTINGS.APP_UPDATE_TITLE',
        descriptionKey: 'SETTINGS.APP_UPDATE_DESCRIPTION',
        keywords: ['update', 'upgrade', 'nightly', 'channel', 'release'],
        requires: ['desktop'],
        fallbackId: 'version',
    },
    {
        id: 'tmdb-credits',
        section: 'about',
        labelKey: 'SETTINGS.TMDB_CREDITS',
        descriptionKey: 'SETTINGS.TMDB_ATTRIBUTION',
        keywords: ['tmdb', 'credits', 'attribution'],
    },
    {
        id: 'community',
        section: 'about',
        labelKey: 'SETTINGS.COMMUNITY',
        descriptionKey: 'SETTINGS.COMMUNITY_DESCRIPTION',
        keywords: ['github', 'telegram', 'help', 'feedback', 'bug'],
    },
    {
        id: 'support',
        section: 'about',
        labelKey: 'SETTINGS.SUPPORT_TITLE',
        descriptionKey: 'SETTINGS.SUPPORT_DESCRIPTION',
        keywords: ['donate', 'sponsor', 'support'],
    },
];
