import { SettingsSearchEntry } from './settings-search.types';

const MPV = ['mpv', 'external player'];
const VLC = ['vlc', 'external player'];

/** Playback section rows, in page order. */
export const PLAYBACK_SETTINGS_SEARCH_ENTRIES: readonly SettingsSearchEntry[] =
    [
        {
            id: 'video-player',
            section: 'playback',
            labelKey: 'SETTINGS.VIDEO_PLAYER_LABEL',
            descriptionKey: 'SETTINGS.VIDEO_PLAYER_DESCRIPTION',
            keywords: [
                'player',
                'engine',
                'mpv',
                'vlc',
                'videojs',
                'html5',
                'artplayer',
            ],
        },
        {
            id: 'stream-format',
            section: 'playback',
            labelKey: 'SETTINGS.STREAM_FORMAT',
            descriptionKey: 'SETTINGS.STREAM_FORMAT_DESCRIPTION',
            keywords: ['hls', 'm3u8', 'mpeg-ts', 'ts', 'format'],
        },
        {
            id: 'web-player-shared-controls',
            section: 'playback',
            labelKey: 'SETTINGS.WEB_PLAYER_SHARED_CONTROLS',
            descriptionKey: 'SETTINGS.WEB_PLAYER_SHARED_CONTROLS_DESCRIPTION',
            keywords: ['controls', 'overlay', 'skin'],
            fallbackId: 'video-player',
        },
        {
            id: 'player-ambient-mode',
            section: 'playback',
            labelKey: 'SETTINGS.PLAYER_AMBIENT_MODE',
            descriptionKey: 'SETTINGS.PLAYER_AMBIENT_MODE_DESCRIPTION',
            keywords: ['ambient', 'glow', 'backlight'],
            fallbackId: 'video-player',
        },
        {
            id: 'detail-trailer-backdrop',
            section: 'playback',
            labelKey: 'SETTINGS.PLAY_TRAILERS_IN_BACKGROUND',
            descriptionKey: 'SETTINGS.PLAY_TRAILERS_IN_BACKGROUND_DESCRIPTION',
            keywords: ['trailer', 'youtube', 'backdrop', 'details'],
            fallbackId: 'video-player',
        },
        {
            id: 'player-up-next-rail',
            section: 'playback',
            labelKey: 'SETTINGS.PLAYER_UP_NEXT_RAIL',
            descriptionKey: 'SETTINGS.PLAYER_UP_NEXT_RAIL_DESCRIPTION',
            keywords: ['up next', 'next episode', 'autoplay'],
            fallbackId: 'video-player',
        },
        {
            id: 'player-up-next-card',
            section: 'playback',
            labelKey: 'SETTINGS.PLAYER_UP_NEXT_CARD',
            descriptionKey: 'SETTINGS.PLAYER_UP_NEXT_CARD_DESCRIPTION',
            keywords: ['up next', 'next episode', 'popup'],
            fallbackId: 'video-player',
        },
        {
            id: 'fullscreen-channel-panel',
            section: 'playback',
            labelKey: 'SETTINGS.FULLSCREEN_CHANNEL_PANEL',
            descriptionKey: 'SETTINGS.FULLSCREEN_CHANNEL_PANEL_DESCRIPTION',
            keywords: ['fullscreen', 'channel list', 'zapping'],
            fallbackId: 'video-player',
        },
        {
            id: 'vod-auto-failover',
            section: 'playback',
            labelKey: 'SETTINGS.VOD_AUTO_FAILOVER',
            descriptionKey: 'SETTINGS.VOD_AUTO_FAILOVER_DESCRIPTION',
            keywords: ['failover', 'fallback', 'mirror', 'retry', 'movie'],
            requires: ['vod-multi-source'],
            fallbackId: 'video-player',
        },
        {
            id: 'external-player-double-click',
            section: 'playback',
            labelKey: 'SETTINGS.OPEN_EXTERNAL_PLAYER_ON_DOUBLE_CLICK',
            descriptionKey:
                'SETTINGS.OPEN_EXTERNAL_PLAYER_ON_DOUBLE_CLICK_DESCRIPTION',
            keywords: ['double click', ...MPV, ...VLC],
            requires: ['managed-external-players'],
            fallbackId: 'video-player',
        },
        {
            id: 'show-external-playback-bar',
            section: 'playback',
            labelKey: 'SETTINGS.SHOW_EXTERNAL_PLAYBACK_BAR',
            descriptionKey: 'SETTINGS.SHOW_EXTERNAL_PLAYBACK_BAR_DESCRIPTION',
            keywords: ['playback bar', 'footer', ...MPV, ...VLC],
            requires: ['desktop'],
        },
        {
            id: 'embedded-mpv-frame-copy',
            section: 'playback',
            labelKey: 'SETTINGS.EMBEDDED_MPV_FRAME_COPY',
            descriptionKey: 'SETTINGS.EMBEDDED_MPV_FRAME_COPY_DESCRIPTION',
            keywords: ['mpv', 'gpu', 'rendering', 'compatibility'],
            requires: ['embedded-mpv-frame-copy'],
        },
        {
            id: 'embedded-mpv-extra-options',
            section: 'playback',
            labelKey: 'SETTINGS.EMBEDDED_MPV_EXTRA_OPTIONS',
            descriptionKey: 'SETTINGS.EMBEDDED_MPV_EXTRA_OPTIONS_DESCRIPTION',
            keywords: ['mpv', 'options', 'config', 'hwdec', 'arguments'],
            requires: ['embedded-mpv'],
            fallbackId: 'video-player',
        },
        {
            id: 'embedded-mpv-auto-reconnect',
            section: 'playback',
            labelKey: 'SETTINGS.EMBEDDED_MPV_AUTO_RECONNECT',
            descriptionKey: 'SETTINGS.EMBEDDED_MPV_AUTO_RECONNECT_DESCRIPTION',
            keywords: ['mpv', 'reconnect', 'retry', 'buffering'],
            requires: ['embedded-mpv'],
            fallbackId: 'video-player',
        },
        {
            id: 'recording-folder',
            section: 'playback',
            labelKey: 'SETTINGS.RECORDING_FOLDER_LABEL',
            descriptionKey: 'SETTINGS.RECORDING_FOLDER_DESCRIPTION',
            keywords: ['recording', 'record', 'dvr', 'folder', 'directory'],
            requires: ['desktop'],
        },
        {
            id: 'mpv-player-path',
            section: 'playback',
            labelKey: 'SETTINGS.MPV_PLAYER_PATH_LABEL',
            descriptionKey: 'SETTINGS.MPV_PLAYER_PATH_DESCRIPTION',
            keywords: [...MPV, 'path', 'executable', 'binary'],
            requires: ['external-player-paths'],
            fallbackId: 'video-player',
        },
        {
            id: 'mpv-player-arguments',
            section: 'playback',
            labelKey: 'SETTINGS.MPV_PLAYER_ARGUMENTS_LABEL',
            descriptionKey: 'SETTINGS.MPV_PLAYER_ARGUMENTS_DESCRIPTION',
            keywords: [...MPV, 'arguments', 'flags', 'command line'],
            requires: ['external-player-paths'],
            fallbackId: 'video-player',
        },
        {
            id: 'mpv-reuse-instance',
            section: 'playback',
            labelKey: 'SETTINGS.MPV_REUSE_INSTANCE_LABEL',
            descriptionKey: 'SETTINGS.MPV_REUSE_INSTANCE_DESCRIPTION',
            keywords: [...MPV, 'single window', 'instance'],
            requires: ['external-player-paths'],
            fallbackId: 'video-player',
        },
        {
            id: 'vlc-player-path',
            section: 'playback',
            labelKey: 'SETTINGS.VLC_PLAYER_PATH_LABEL',
            descriptionKey: 'SETTINGS.VLC_PLAYER_PATH_DESCRIPTION',
            keywords: [...VLC, 'path', 'executable', 'binary'],
            requires: ['external-player-paths'],
            fallbackId: 'video-player',
        },
        {
            id: 'vlc-player-arguments',
            section: 'playback',
            labelKey: 'SETTINGS.VLC_PLAYER_ARGUMENTS_LABEL',
            descriptionKey: 'SETTINGS.VLC_PLAYER_ARGUMENTS_DESCRIPTION',
            keywords: [...VLC, 'arguments', 'flags', 'command line'],
            requires: ['external-player-paths'],
            fallbackId: 'video-player',
        },
        {
            id: 'vlc-reuse-instance',
            section: 'playback',
            labelKey: 'SETTINGS.VLC_REUSE_INSTANCE_LABEL',
            descriptionKey: 'SETTINGS.VLC_REUSE_INSTANCE_DESCRIPTION',
            keywords: [...VLC, 'single window', 'instance'],
            requires: ['external-player-paths'],
            fallbackId: 'video-player',
        },
    ];
