declare const RUNTIME_PROBE_CONTRACT: Readonly<{
    readonly RUNTIME_PROBE_MAX_BUFFER_BYTES: 16777216;
    readonly RUNTIME_PROBE_TIMEOUT_MS: 3000;
    readonly PACKAGE_VERIFICATION_PROBE_TIMEOUT_MS: 15000;
    readonly PACKAGE_VERIFICATION_PROBE_MAX_ATTEMPTS: 2;
}>;

export = RUNTIME_PROBE_CONTRACT;
