---
services:
  iptvnator:
    image: 4gray/iptvnator:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "4333:80"
    environment:
      BACKEND_URL: /api
      CLIENT_URL: http://localhost:4333
